<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html lang="en">
<c:set var="title" value="JSON Generator" scope="request" />
<c:import url="includes/head.jsp" />

<body>
<div class="container-fluid px-0">
    <c:import url="includes/header.jsp" />

    <main class="p-3">
        <c:choose>
            <c:when test="${command != null}">
                <h2>'${command.name}' Generated by ${owner}</h2>

                <p>To run this command in your world, copy the text below and
                    paste it into the chat or into a command block with cheats
                    enabled.</p>

                <c:if test="${!command.shared}">
                    <p class="text-danger">This command is not shared, so
                        only you can view it. Make it public if you want to
                        share the command with others.</p>
                </c:if>

                <div class="form-group">
                    <label for="command">Command</label>
                    <textarea id="command" class="form-control" readonly>${command.value}</textarea>
                </div>

                <p>You can generate your own command <a href="generate">here</a>.</p>

                <p>See a problem or something inappropriate? Report it <a href="report">here</a>.</p>

                <c:if test="${isAdmin != null && isAdmin}">
                    <h2>Admin Controls</h2>

                    <p>If the command is not appropriate for all users, be sure to unshare the command. While this
                        behavior is not encouraged, there is nothing wrong with saving these types of commands to the
                        system. If, however, the command is spam or otherwise an attempt to harm the system, be sure
                        to delete it. If the user continues this destructive behavior, you can delete their account.</p>

                    <form method="POST" action="adminedit">
                        <h3>Admin Report</h3>

                        <p><span class="text-danger">*</span> Indicates required field</p>

                        <p><span class="text-danger">*</span>Select the action to take on this command post.</p>

                        <div class="form-group form-check">
                            <input type="radio" id="unshare" class="form-check-input" name="mode" value="unshare" required checked>
                            <label for="unshare" class="form-check-label">Unshare Command</label>
                        </div>

                        <div class="form-group form-check">
                            <input type="radio" id="deletePost" class="form-check-input" name="mode" value="deletePost">
                            <label for="deletePost" class="form-check-label">Delete Post</label>
                        </div>

                        <div class="form-group form-check">
                            <input type="radio" id="deleteProfile" class="form-check-input" name="mode" value="deleteProfile">
                            <label for="deleteProfile" class="form-check-label">Delete Profile</label>
                        </div>

                        <div class="form-group">
                            <label for="reason"><span class="text-danger">*</span>Reason for Action</label>
                            <textarea id="reason" class="form-control" name="reason" required></textarea>
                        </div>

                        <input type="hidden" name="userId" value="${ownerId}">
                        <input type="hidden" name="commandId" value="${command.id}">

                        <input type="submit" class="btn btn-primary" value="Submit Action">

                        <c:if test="${feedback != null}">
                            <p class="text-success">${feedback}</p>
                        </c:if>

                    </form>
                </c:if>

            </c:when>

            <c:otherwise>
                <h2>Unable to View Command</h2>
                <p>This command cannot be shown. If this is incorrect, you can
                    report a problem <a href="report">here</a>.</p>
            </c:otherwise>
        </c:choose>
    </main>

    <c:import url="includes/footer.jsp" />
</div>
</body>

<c:import url="includes/scripts.jsp" />

</html>
