<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html lang="en">
<c:set var="title" value="JSON Generator" scope="request" />
<c:import url="includes/head.jsp"></c:import>

<body>
<div class="container-fluid px-0">
    <c:import url="includes/header.jsp"></c:import>

    <main class="p-3">
        <c:choose>
            <c:when test="${command != null}">
                <h2>${command.name} Generated by ${user}</h2>

                <p>To run this command in your world, copy the text below and
                    paste it into the chat or into a command block with cheats
                    enabled.</p>

                <textarea readonly>${command.value}</textarea>

                <p>You can generate your own command <a href="generate">here</a>.</p>

                <p>See a problem or something inappropriate? Report it <a href="report">here</a>.</p>
            </c:when>

            <c:otherwise>
                <h2>Unable to View Command</h2>
                <p>This command cannot be shown. If this is incorrect, you can
                    report a problem <a href="report">here</a>.</p>
            </c:otherwise>
        </c:choose>
    </main>

    <c:import url="includes/footer.jsp"></c:import>
</div>
</body>

<c:import url="includes/scripts.jsp"></c:import>

</html>
